### ISSUE TITLE
Not clear how to create fread.ext4 file

### ISSUE THREAD

**Issue by kaloyan-raev** [fread-ink/fread-userland#2]
The [fread-vagrant README](https://github.com/fread-ink/fread-vagrant/blob/master/README.md#putting-it-all-together) files says I should have a `fread.ext4` after following the instructions in this project.

I am at the state of [Compiling glibc](https://github.com/fread-ink/fread-userland#compiling-glibc) and I am not sure how to proceed. I'd appreciate any help.

**Comment by Juul** [comment]
Ah! I forgot that I hadn't written that part of the docs.

The cross-compile environment created in the `qemu_chroot` directory is very similar to the actual fread userland. The biggest difference is that it has a lot of extra packages that aren't needed and as such it's a lot bigger than it needs to be. However, for development purposes it will work fine. I have some notes on how to create an extremely minimal userland and I will ensure that they work and add them to the README.md later. 

Here are the basics:

```
du -ch qemu_chroot # find the size of the userland
# For count= you should use the size of the userland + 100 MB (for some free space)
dd if=/dev/zero of=fread.ext4 bs=1M count=<size in MB> # create a blank file
mkfs.ext4 fread.ext4 # create an ext4 filesystem in the blank file
tune2fs -c 0 -i 0 ./fread.ext4 # disable automatic fsck on mount (since it doesn't yet work)
sudo mount -o loop fread.ext4 /mnt # loop-mount the file
sudo cp -a qemu_chroot/* /mnt/ # copy the userland into the loop-mounted ext4 file
sudo rm /mnt/usr/bin/qemu-arm-static # delete the emulatorc
sudo cp makenodes.sh /mnt/ # ATTENTION: Copy this from the fread-initrd git repo
cd /mnt
sudo ./makenodes.sh # populate /dev
sudo umount /mnt #unmount
```

I _think_ this will get your a working userland but I see that I didn't include a proper init file in fread-initrd so it will simply drop you to a shell (only available over serial terminal) then you will have to manually figure out how to mount and chroot into the real userland. This is actually sorta complicated but I can't find the proper init file on my laptop right now. I'll see if I can find it when I get home but I might not get home until tomorrow evening.

**Comment by Juul** [comment]
Ah I found it. I don't think this will work automatically without some tweaking so for now, after booting with `kexec` and getting a prompt via serial terminal, try entering the following commands manually. I recommend pasting them one at a time and then hitting enter since some of these require waiting for the previous command to finish.

```
# Mount the kindle's fat32 partition so we can access the fread.ext4 file
/sbin/losetup -o 8192 /dev/loop/0 /dev/mmcblk0p4
/bin/mkdir -p /mnt/us
/bin/mount -t vfat -o defaults,noatime,utf8,noexec,shortname=mixed /dev/loop/0 /mnt/us

# Mount the fread userland
/sbin/losetup /dev/loop/1 /mnt/us/fread.ext4
/bin/mkdir -p /mnt/fread
/bin/mount -t ext4 -o defaults,noatime /dev/loop/1 /mnt/fread

# Could not get pivot_root working so using this for now
/bin/umount /proc
/bin/umount /sys
chroot /mnt/fread
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
```

**Comment by Juul** [comment]
I wrote up some notes on a better init file in [this issue](https://github.com/fread-ink/fread-initrd/issues/2) in the fread-initrd repo.

**Comment by Juul** [comment]
Alright I added some more info to the readme on how to install (or build from scratch) the xorg driver. There's still some stuff missing on how to load the kernel e-ink modules correctly and start the X server but I'm not sure I'll have much more time this weekend. 

Are you aware that you do not have to compile glibc? I made a pre-compiled version available in the fread apt repository. As it says in the readme (but maybe not clearly enough), inside of the qemu_chroot you can add the fread apt repo like so:

Add the following lines to /etc/apt/sources.list

```
deb https://fread.ink/apt enheduanna main
deb-src https://fread.ink/apt enheduanna main
```

Add the fread.ink apt gpg key:

```
wget -qO - https://fread.ink/fread-apt-key.pub | apt-key add -
```

Now you can update your apt sources and install the fread glibc and the xorg driver:

```
apt update
apt install libc-bin libc-dev-bin libc6 libc6-dev xserver-xorg-video-imx
```

I want to change the instructions and scripts in this repo so it starts as an instruction on how to create a minimal fread userland and then let's you install all of the build tools for development as an option, but for now getting things working is more important than saving disk-space on the kindle.

Let me know if you run into more problems.

**Comment by kaloyan-raev** [comment]
Thanks for taking the time to describe all these!

I believe I followed the instructions correctly, but in the end the size of the `qemu_chroot` directory was 1.4 GB. +100 MB for the `fread.ext4` file and it goes to 1.5 GB. This is larger than the Kindle's `/mnt/us` partition, which is 1.4 GB. And much larger than the Kindles main partition which is just 384 MB.

Could you give any hints what I can safely remove from the `qemu_chroot` directory before creating the `fread.ext4` file?

**Comment by Juul** [comment]
Ah! I'll try to update the instructions to show how to make the minimal userland.

**Comment by Juul** [comment]
Alright I updated both the fread-userland and fread-vagrant scripts and instructions and tested everything on a kindle 4 nt. You should now be able to create a minimal userland and boot into it. There were problems both with the initramfs/initrd and with the kexec binary that I resolved. You could recompile everything or just [download the pre-compiled binaries](https://github.com/fread-ink/fread-vagrant#pre-compiled). If you do recompile then for fread-initrd you will have to pull the newest changes from the repo, then delete the entire `buildroot-2016.02/output` directory and recompile from scratch. For fread-kernel-k4 you can get away with just re-running `build.sh`. 

For now you will have to build the userland yourself using the fread-userland instructions.

What's still missing:

* Auto-loading kernel modules on boot (proper userland init file)
* Xorg config file
* Window manager (awesome) and auto screen refresh on XDamage events

I might have some time this week but otherwise it will have to wait until next weekend.
